---
version: '2'
services:
  db:
    image: 'mysql:5.6'
    environment:
      MYSQL_ROOT_PASSWORD: 'stompy'
      MYSQL_DATABASE: 'helloworld'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
  router:
    build: 'proxysql'
    command: '--initial -c /etc/proxysql.cfg -D /var/lib/proxysql'
    volumes:
      - './proxysql.router.cfg:/etc/proxysql.cfg'
    links:
      - db
  forwarder:
    build: 'proxysql'
    command: '--initial -c /etc/proxysql.cfg -D /var/lib/proxysql'
    volumes:
      - './proxysql.forwarder.cfg:/etc/proxysql.cfg'
    links:
      - router
  test:
    build: 'test'
    links:
      - db
      - router
      - forwarder
