---
version: '2'
services:
  db:
    image: 'mysql:5.6'
    environment:
      MYSQL_ROOT_PASSWORD: 'stompy'
      MYSQL_DATABASE: 'helloworld'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
  router:
    build: 'proxysql'
    cap_add:
      - SYS_PTRACE
    volumes:
      - './proxysql/proxysql:/opt/proxysql'
      - './proxysql.router.cfg:/etc/proxysql.cfg'
    links:
      - db
  test:
    build: 'test'
    volumes:
      - './test:/root'
    links:
      - db
      - router
